version: '3.3'
services:
  app:
#    environment:
#    - XDEBUG_CONFIG
    build:
      dockerfile: docker/app/Dockerfile
      context: .
    volumes:
#    - composer_cache:/root/.composer
      - /var/www/medkey/vendor
      - .:/var/www/medkey
    ports:
      - 8084:80
  db:
    image: postgres:11.2
    restart: always
    volumes:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: medkey
      PGDATA: /var/lib/postgresql/data