version: '3.7'
services:
  mk:
#    environment:
#    - XDEBUG_CONFIG
    build:
      dockerfile: docker/backend/Dockerfile
      context: .
    volumes:
#      - type: volume
#        source: vendor
#        target: /var/www/medkey/vendor
#      - type: volume
#        source: node_modules
#        target: /var/www/medkey/frontend/node_modules
      - type: volume
        source: static
        target: /var/www/medkey/web/bundles
      - type: bind
        source: .
        target: /var/www/medkey
#      - type: bind
#        source: .env.prod # TODO remove
#        target: /var/www/medkey/.env
    ports:
      - 8090:80
    depends_on:
      - mk_db
  mk_db:
    image: postgres:11.2
    restart: always
    ports:
      - 6582:5432
    volumes:
      - ../db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: medkey
      PGDATA: /var/lib/postgresql/data
volumes:
#  vendor:
#  node_modules:
  static: